name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

# Required for Codecov OIDC uploads and generally safe defaults
permissions:
  contents: read
  id-token: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Run checks
        run: make check

  tests-and-type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show tool versions (debug)
        run: |
          python --version
          uv --version

      - name: Run tests
        run: uv run python -m pytest tests --cov --cov-config=pyproject.toml --cov-report=xml --junitxml=junit.xml

      - name: Check typing
        run: uv run mypy

      # --- Codecov upload (only Python 3.11) ---
      # Upload coverage only when it's NOT a fork PR (tokenless/OIDC upload).
      - name: Upload coverage to Codecov (3.11, non-fork)
        if: ${{ matrix.python-version == '3.11' && (github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork) }}
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          # Uses GitHub OIDC; no token required for non-fork runs.
          use_oidc: true

      # Save coverage as artifact on fork PRs (no upload attempt to avoid permission issues).
      - name: Save coverage artifact (3.11, fork PR)
        if: ${{ matrix.python-version == '3.11' && github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml

      # Optional test results upload to Codecov (skip on forks to avoid tokenless failure).
      - name: Upload test results to Codecov (3.11, non-fork)
        if: ${{ matrix.python-version == '3.11' && (github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork) && !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          # This action can work without a token on trusted runs; if you prefer token, you can add it here.
          # token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Check if documentation can be built
        run: uv run mkdocs build -s
