name: Deploy MkDocs

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install uv
          uv venv
          uv pip install mkdocs mkdocs-material mkdocstrings[python]

      - name: Build MkDocs
        run: uv run mkdocs build --strict

      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force
