name: Deploy MkDocs

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install uv
          uv venv
          uv pip install mkdocs mkdocs-material mkdocstrings[python]

      - name: Build MkDocs
        run: uv run mkdocs build --strict

      #- name: Deploy to GitHub Pages
      #  run: uv run mkdocs gh-deploy --force
      # Note that GH_PAT is a secret that you need to create in your repository settings
      - name: Deploy to GitHub Pages
        env:
            GIT_USER: "github-actions[bot]"
            GIT_EMAIL: "github-actions[bot]@users.noreply.github.com"
            GH_PAT: ${{ secrets.GH_PAT }}
        run: |
            git config --global user.name "$GIT_USER"
            git config --global user.email "$GIT_EMAIL"
            git remote set-url origin https://x-access-token:$GH_PAT@github.com/dave-Lab-and-Engineering/python-build-utils.git
            uv run mkdocs gh-deploy --force --remote-branch gh-pages


